version: '3.8'

services:
  servidor:
    build: 
      context: ./server 
    container_name: servidor_web
    ports:
      - "8080:8080"
    networks:
      - minha_rede_docker

  cliente:
    build: 
      context: ./client
    container_name: cliente_requisitante
    depends_on:
      - servidor 
    networks:
      - minha_rede_docker

networks:
  minha_rede_docker:
    driver: bridge